version: '3.4'

networks:
  web:
    external:
      name: web
services:
  hydra:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hydra.entrypoints=http"
      - "traefik.http.routers.hydra.rule=Host(`hydra.example.com`)"
      - "traefik.http.middlewares.hydra-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hydra.middlewares=hydra-https-redirect"
      - "traefik.http.routers.hydra-secure.entrypoints=https"
      - "traefik.http.routers.hydra-secure.rule=Host(`hydra.example.com`)"
      - "traefik.http.routers.hydra-secure.tls=true"
      - "traefik.http.routers.hydra-secure.service=hydra"
      - "traefik.http.services.hydra.loadbalancer.server.port=4444"
      - "traefik.docker.network=web"
    networks:
      web:
  hydra-migrate:
    labels:
    - "traefik.enable=false"

  postgres:
    labels:
      - "traefik.enable=false"
