version: "3.4"

services:
  traefik:
    image: traefik:v2.2
    security_opt:
      - no-new-privileges:true
    container_name: traefik
    restart: unless-stopped
    # command: 
      # --api.insecure=true --providers.docker
    networks:
      - web
      - internal
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DO_AUTH_TOKEN=YOUR_DIGITALOCEAN_AUTH_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - TRAEFIK_PATH/traefik.yml:/traefik.yml:ro
      - TRAEFIK_PATH/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=le"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=example.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.example.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  web:
    external:
      name: web
  internal:
    external:
      name: internal
